from __future__ import annotations
from datetime import datetime, timezone
from sqlalchemy import String,Integer,Float,DateTime,Boolean,Text,JSON,Index
from sqlalchemy.orm import Mapped,mapped_column
from backend.database.db import Base
def now_utc(): return datetime.now(timezone.utc)
class User(Base):
    __tablename__="users"; id:Mapped[int]=mapped_column(Integer,primary_key=True); user_id:Mapped[str]=mapped_column(String(64),unique=True,index=True); username:Mapped[str]=mapped_column(String(120),unique=True,index=True); password_hash:Mapped[str]=mapped_column(String(255)); role:Mapped[str]=mapped_column(String(32),default="analyst"); active:Mapped[bool]=mapped_column(Boolean,default=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now_utc)
class Device(Base):
    __tablename__="devices"; id:Mapped[int]=mapped_column(Integer,primary_key=True); device_id:Mapped[str]=mapped_column(String(64),unique=True,index=True); hostname:Mapped[str|None]=mapped_column(String(150),nullable=True); platform:Mapped[str|None]=mapped_column(String(80),nullable=True); owner_user_id:Mapped[str|None]=mapped_column(String(64),nullable=True,index=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now_utc)
class IPAddress(Base):
    __tablename__="ip_addresses"; id:Mapped[int]=mapped_column(Integer,primary_key=True); ip:Mapped[str]=mapped_column(String(64),unique=True,index=True); reputation:Mapped[float]=mapped_column(Float,default=0.0); source:Mapped[str|None]=mapped_column(String(80),nullable=True)
class SessionRecord(Base):
    __tablename__="sessions"; id:Mapped[int]=mapped_column(Integer,primary_key=True); session_id:Mapped[str]=mapped_column(String(64),unique=True,index=True); user_id:Mapped[str]=mapped_column(String(64),index=True); device_id:Mapped[str|None]=mapped_column(String(64),nullable=True,index=True); source_ip:Mapped[str|None]=mapped_column(String(64),nullable=True,index=True); started_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now_utc); ended_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); active:Mapped[bool]=mapped_column(Boolean,default=True)
class Event(Base):
    __tablename__="events"; id:Mapped[int]=mapped_column(Integer,primary_key=True); event_id:Mapped[str]=mapped_column(String(64),unique=True,index=True); timestamp:Mapped[datetime]=mapped_column(DateTime(timezone=True),index=True); event_type:Mapped[str]=mapped_column(String(64),index=True); user_id:Mapped[str|None]=mapped_column(String(64),nullable=True,index=True); device_id:Mapped[str|None]=mapped_column(String(64),nullable=True,index=True); source_ip:Mapped[str|None]=mapped_column(String(64),nullable=True,index=True); destination_ip:Mapped[str|None]=mapped_column(String(64),nullable=True); resource:Mapped[str|None]=mapped_column(String(255),nullable=True); action:Mapped[str|None]=mapped_column(String(120),nullable=True); status:Mapped[str|None]=mapped_column(String(64),nullable=True); severity:Mapped[str]=mapped_column(String(32),default="low"); asset_id:Mapped[str|None]=mapped_column(String(64),nullable=True,index=True); session_id:Mapped[str|None]=mapped_column(String(64),nullable=True,index=True); cve_id:Mapped[str|None]=mapped_column(String(40),nullable=True,index=True); metadata_json:Mapped[dict]=mapped_column(JSON,default=dict); rule_score:Mapped[float]=mapped_column(Float,default=0.0); anomaly_score:Mapped[float]=mapped_column(Float,default=0.0); correlation_score:Mapped[float]=mapped_column(Float,default=0.0); threat_score:Mapped[float]=mapped_column(Float,default=0.0); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now_utc); __table_args__=(Index("ix_events_user_time","user_id","timestamp"),Index("ix_events_device_time","device_id","timestamp"))
class EventFeature(Base):
    __tablename__="event_features"; id:Mapped[int]=mapped_column(Integer,primary_key=True); event_id:Mapped[str]=mapped_column(String(64),unique=True,index=True); features:Mapped[dict]=mapped_column(JSON,default=dict)
class Rule(Base):
    __tablename__="rules"; id:Mapped[int]=mapped_column(Integer,primary_key=True); rule_id:Mapped[str]=mapped_column(String(64),unique=True,index=True); name:Mapped[str]=mapped_column(String(160)); description:Mapped[str]=mapped_column(Text); severity:Mapped[str]=mapped_column(String(32),default="medium"); score:Mapped[float]=mapped_column(Float,default=10.0); enabled:Mapped[bool]=mapped_column(Boolean,default=True); conditions:Mapped[dict]=mapped_column(JSON,default=dict)
class RuleMatch(Base):
    __tablename__="rule_matches"; id:Mapped[int]=mapped_column(Integer,primary_key=True); event_id:Mapped[str]=mapped_column(String(64),index=True); rule_id:Mapped[str]=mapped_column(String(64),index=True); matched_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now_utc); evidence:Mapped[dict]=mapped_column(JSON,default=dict); score:Mapped[float]=mapped_column(Float,default=0.0)
class Incident(Base):
    __tablename__="incidents"; id:Mapped[int]=mapped_column(Integer,primary_key=True); incident_id:Mapped[str]=mapped_column(String(64),unique=True,index=True); title:Mapped[str]=mapped_column(String(255)); description:Mapped[str]=mapped_column(Text); risk_score:Mapped[float]=mapped_column(Float,default=0.0); severity:Mapped[str]=mapped_column(String(32),default="low"); status:Mapped[str]=mapped_column(String(32),default="NEW",index=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now_utc); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now_utc,onupdate=now_utc); affected_users:Mapped[list]=mapped_column(JSON,default=list); affected_devices:Mapped[list]=mapped_column(JSON,default=list); affected_ips:Mapped[list]=mapped_column(JSON,default=list); affected_assets:Mapped[list]=mapped_column(JSON,default=list); related_vulnerabilities:Mapped[list]=mapped_column(JSON,default=list); evidence:Mapped[list]=mapped_column(JSON,default=list); recommended_action:Mapped[str]=mapped_column(__import__('sqlalchemy').Text,default="Review incident evidence and validate affected identity.")
class IncidentEvent(Base):
    __tablename__="incident_events"; id:Mapped[int]=mapped_column(Integer,primary_key=True); incident_id:Mapped[str]=mapped_column(String(64),index=True); event_id:Mapped[str]=mapped_column(String(64),index=True); relevance_score:Mapped[float]=mapped_column(Float,default=0.0)
class Asset(Base):
    __tablename__="assets"; id:Mapped[int]=mapped_column(Integer,primary_key=True); asset_id:Mapped[str]=mapped_column(String(64),unique=True,index=True); hostname:Mapped[str|None]=mapped_column(String(160),nullable=True); ip:Mapped[str|None]=mapped_column(String(64),nullable=True); type:Mapped[str]=mapped_column(String(80),default="server"); criticality:Mapped[str]=mapped_column(String(32),default="MEDIUM"); internet_exposed:Mapped[bool]=mapped_column(Boolean,default=False); owner:Mapped[str|None]=mapped_column(String(120),nullable=True); environment:Mapped[str]=mapped_column(String(64),default="lab")
class Vulnerability(Base):
    __tablename__="vulnerabilities"; id:Mapped[int]=mapped_column(Integer,primary_key=True); cve_id:Mapped[str]=mapped_column(String(40),unique=True,index=True); description:Mapped[str]=mapped_column(Text,default=""); cvss:Mapped[float|None]=mapped_column(Float,nullable=True); severity:Mapped[str]=mapped_column(String(32),default="UNKNOWN"); kev:Mapped[bool]=mapped_column(Boolean,default=False); affected_products:Mapped[list]=mapped_column(JSON,default=list); published_at:Mapped[str|None]=mapped_column(String(64),nullable=True); last_modified:Mapped[str|None]=mapped_column(String(64),nullable=True); source:Mapped[str]=mapped_column(String(64),default="local")
class AssetVulnerability(Base):
    __tablename__="asset_vulnerabilities"; id:Mapped[int]=mapped_column(Integer,primary_key=True); asset_id:Mapped[str]=mapped_column(String(64),index=True); cve_id:Mapped[str]=mapped_column(String(40),index=True); observed_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now_utc); fixed:Mapped[bool]=mapped_column(Boolean,default=False)
class RiskScore(Base):
    __tablename__="risk_scores"; id:Mapped[int]=mapped_column(Integer,primary_key=True); subject_type:Mapped[str]=mapped_column(String(32),index=True); subject_id:Mapped[str]=mapped_column(String(64),index=True); score:Mapped[float]=mapped_column(Float,default=0.0); factors:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now_utc)
class ForensicNode(Base):
    __tablename__="forensic_nodes"; id:Mapped[int]=mapped_column(Integer,primary_key=True); node_id:Mapped[str]=mapped_column(String(128),unique=True,index=True); node_type:Mapped[str]=mapped_column(String(64),index=True); label:Mapped[str]=mapped_column(String(255)); properties:Mapped[dict]=mapped_column(JSON,default=dict)
class ForensicEdge(Base):
    __tablename__="forensic_edges"; id:Mapped[int]=mapped_column(Integer,primary_key=True); source_node_id:Mapped[str]=mapped_column(String(128),index=True); target_node_id:Mapped[str]=mapped_column(String(128),index=True); relationship:Mapped[str]=mapped_column(String(80)); properties:Mapped[dict]=mapped_column(JSON,default=dict)
class AuditLog(Base):
    __tablename__="audit_logs"; id:Mapped[int]=mapped_column(Integer,primary_key=True); actor:Mapped[str|None]=mapped_column(String(120),nullable=True,index=True); action:Mapped[str]=mapped_column(String(120),index=True); resource:Mapped[str|None]=mapped_column(String(255),nullable=True); details:Mapped[dict]=mapped_column(JSON,default=dict); timestamp:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now_utc)
class PQCBenchmark(Base):
    __tablename__="pqc_benchmarks"; id:Mapped[int]=mapped_column(Integer,primary_key=True); algorithm:Mapped[str]=mapped_column(String(120),index=True); operation:Mapped[str]=mapped_column(String(80)); elapsed_ms:Mapped[float]=mapped_column(Float); public_key_bytes:Mapped[int|None]=mapped_column(Integer,nullable=True); private_key_bytes:Mapped[int|None]=mapped_column(Integer,nullable=True); signature_or_ciphertext_bytes:Mapped[int|None]=mapped_column(Integer,nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now_utc)
